import { z } from "zod";

export const invoiceItemSchema = z.object({
  productId: z.string().optional().or(z.literal("")),
  description: z.string().min(1, "Description is required"),
  quantity: z.coerce.number().min(0.001, "Quantity must be greater than 0"),
  unitPrice: z.coerce.number().min(0, "Unit price must be positive"),
  discount: z.coerce.number().min(0).default(0),
  taxSystemIds: z.array(z.string()).default([]),
});

export const invoiceSchema = z.object({
  customerId: z.string().min(1, "Customer is required"),
  invoiceNumber: z.string().optional(), // Generated by backend if not provided
  status: z.enum(["DRAFT", "SENT", "VIEWED", "PARTIAL_PAID", "PAID", "OVERDUE", "CANCELLED", "REFUNDED"]).default("DRAFT"),
  issueDate: z.coerce.date().default(() => new Date()),
  dueDate: z.coerce.date().optional(),
  items: z.array(invoiceItemSchema).min(1, "At least one item is required"),
  notes: z.string().optional().or(z.literal("")),
  terms: z.string().optional().or(z.literal("")),
  currency: z.string().default("USD"),
});

export type InvoiceFormValues = z.infer<typeof invoiceSchema>;
export type InvoiceItemFormValues = z.infer<typeof invoiceItemSchema>;
